### ISSUE TITLE
Documentation lacks '.header' tag

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-anchornav#14]
js requires a html tag with a class '.header', not documented!

**Comment by beroes** [comment]
Good point @GeorgMeyer23 , having a '.header' element had become necessity after the implementation of 'initialisable' method. The idea behing using a '.header' element is to provide a value to 'showHideNavAt' option. So actually the role of the '.header' is to supply 'showHideNavAt' option with a value (this value is dynamic and reflects the responsive behaviour of the page). The task was to hide and show the anchor nav when the page header is not visible (the user had scrolled the page so that the header is off the window) Initially it was assumed that a static 'showHideNavAt' option value will be used, but this turns out that works only for non responsive pages. In reponsive page the height of the header changes in different breakpoints and in accordance to it changes the 'showHideNavAt' option value.

**Comment by ain** [comment]
So I guess this would be yet another benefit of relying on ScrollMagic as it'd support responsive layouts natively?

**Comment by beroes** [comment]
Nope, here the case is different, we just need a div Sizer in our case ('.header') that is observed by the application and its height is used to provide a value for the  'showHideNavAt' setting in responsive manner.
